/* C3DSpline, CCameraPas, CCharaPas
 *
 * Unité découpée par `make carve` : 143 fonctions, 23780 octets, de
 * 0x00254660 à 0x0025A670. Chacune garde les instructions du disque
 * jusqu'à ce qu'elle soit écrite en C++, et l'ordre est celui des adresses,
 * que l'éditeur de liens attend.
 */

#include "common.h"

/* La pile de l'interpréteur de script d'objet. Les commandes qui ne rendent
 * qu'un code de retour ne la déréférencent pas : sa disposition reste à
 * établir. */
struct SPI_STACK;

INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_TEXDATA_CLEAR__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_CLEAR__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_TEXDATA_MALLOC__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_TEXNAME__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_TEXDATA_OFFSET__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_TEXDATA__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_MALLOC__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_OFFSET_NO__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_SET__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_PARTNUM__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", menu_texdata_to_formpart_copy__FP18MENUFORMPARTS_TYPE);
INCLUDE_ASM("nonmatchings/game/c3dspline", menu_spi_analyze_func_strcut1__FP24MENU_SPI_ANALYZE_STRUCT1Pc);
INCLUDE_ASM("nonmatchings/game/c3dspline", menu_dtype_init__FP16CMenuPosDataFormP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_DTYPE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_MTYPE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_DRAWFLG__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_VIBECNT__FP9SPI_STACKi);
s32 _MENU_FORM_SETEND(SPI_STACK *stack, int argc) {
    return 1;
}
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_MOVERATE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_PUTXY__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_RGBA__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM_RGBA_BIT__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_ACTION_TABLE_NUM__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_ACTION_DEF__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_ACTION_SETACTION__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PARTVIBECNT__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PARTVIBER__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_SHADOW_ONOFF__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _CLIP_WH__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PARTRGBA__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PART_ALPHA_BLEND__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PART_ETCINFO__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PART_BILINEAR__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", MakePartsName__FP9SPI_STACKP18MENUFORMPARTS_TYPE);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PART_DTYPE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_NORMAL__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_NORMAL2__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_CURSOR__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FUNCINFO__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_NUMBER1__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_NUMBER2__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FRMIMG__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FORM__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_ITEM__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_ITEM_CHECKMARK__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FILLBOX__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_FILLBOXINFO__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_WAKU_RECT__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_WAKU_CIRCLE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PARTS_EFF_NUM__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_PARTS_EFFECT__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", MenuDataAnalyze__FPciP9mgCMemory);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_COMMAND_NAME__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_DRAWFLAG__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_RGBA__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_CALCRGBAPARAM__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_FADE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_SETPOS__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_SETACTION__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_PARTSONOFF__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_PARTSONOFF_GRP__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_SWAP__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_FORM_GROUP_SWAP__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_MSGENV__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_MAKEMSG__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_SETABSPOS__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_MSGSETSYSTEMBUFF__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_MSGSETBUFF__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_MSGSETFUCHI__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_MSGSETCURSOR__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_SET_QUESTIONGYOU__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_SET_OPENSPEED__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_INPUT_KEY__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_CURSOR_ONOFF__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_CURSOR_FADE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_WAKUTYPE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_SCENE_FADE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_SE_PLAY__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_INIT_DRAWLIST__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_EXE_RESET_TEXINFO__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", _MENU_DEBUG_PRINTF__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/game/c3dspline", MenuCommandAnalyze__FPciPc);
INCLUDE_ASM("nonmatchings/game/c3dspline", LoadNpcTalkMes__FP9mgCMemory);
INCLUDE_ASM("nonmatchings/game/c3dspline", ResetNpcTalkMes__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetSquareEvent__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", InitEvent__FP6CScene);
INCLUDE_ASM("nonmatchings/game/c3dspline", SetEventScript__FPcPcP9mgCMemory);
INCLUDE_ASM("nonmatchings/game/c3dspline", RunEvent__FiP6CScene);
INCLUDE_ASM("nonmatchings/game/c3dspline", EventDoorLoop__Fii);
INCLUDE_ASM("nonmatchings/game/c3dspline", StartEventSyori__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", SkipEventStart__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", SkipEvent__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", CheckEventSkip__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", EventLoop__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetEventMessage__Fi);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetActiveCamera__Fv);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetCharacter__Fi);
INCLUDE_ASM("nonmatchings/game/c3dspline", InitSplineKey__FP10SPLINE_KEY);
INCLUDE_ASM("nonmatchings/game/c3dspline", __ct__9C3DSplineFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Initialize__9C3DSplineFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", SetUpSpline__9C3DSplineFPA4_fPiif);
INCLUDE_ASM("nonmatchings/game/c3dspline", StepS__9C3DSplineFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Step__9C3DSplineFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetNowXYZ__9C3DSplineFPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", __ct__10CCameraPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", AddCameraPas__10CCameraPasFPfPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", InsCameraPas__10CCameraPasFiPfPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", SetCameraPas__10CCameraPasFiPfPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetCameraPas__10CCameraPasFiPfPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", DelCameraPas__10CCameraPasFi);
INCLUDE_ASM("nonmatchings/game/c3dspline", SetFrame__10CCameraPasFi);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetFrame__10CCameraPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Initialize__10CCameraPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Setup__10CCameraPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Run__10CCameraPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Step__10CCameraPasFPfPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", CheckEnd__10CCameraPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", __ct__9CCharaPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Initialize__9CCharaPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", AddCharaPas__9CCharaPasFPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", Setup__9CCharaPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Run__9CCharaPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", Step__9CCharaPasFPfPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", CheckEnd__9CCharaPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", InsCharaPas__9CCharaPasFiPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", SetCharaPas__9CCharaPasFiPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetCharaPas__9CCharaPasFiPf);
INCLUDE_ASM("nonmatchings/game/c3dspline", DelCharaPas__9CCharaPasFi);
INCLUDE_ASM("nonmatchings/game/c3dspline", SetFrame__9CCharaPasFi);
INCLUDE_ASM("nonmatchings/game/c3dspline", GetFrame__9CCharaPasFv);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsPRDelay__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsSetPos__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsSetRef__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsAHDDelay__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsSetAngle__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsSetHeight__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsSetDist__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsSetAHD__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsMove__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsMove2__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsMoveRef__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsMovePos__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
INCLUDE_ASM("nonmatchings/game/c3dspline", scsMoveAHD__FP12_SEN_CMR_SEQP12CSceneCmrSeq);
