/* CFont, COcclusion
 *
 * Unité découpée par `make carve` : 90 fonctions, 24920 octets, de
 * 0x002D8EE0 à 0x002DF230. Chacune garde les instructions du disque
 * jusqu'à ce qu'elle soit écrite en C++, et l'ordre est celui des adresses,
 * que l'éditeur de liens attend.
 */

#include "common.h"

INCLUDE_ASM("nonmatchings/cfont", CheckKanjiFont__5CFontFi);
INCLUDE_ASM("nonmatchings/cfont", CheckHalfFont__5CFontFi);
INCLUDE_ASM("nonmatchings/cfont", SetDrawSize__5CFontFii);
INCLUDE_ASM("nonmatchings/cfont", SetClearance__5CFontFii);
INCLUDE_ASM("nonmatchings/cfont", SetPos__5CFontFii);
INCLUDE_ASM("nonmatchings/cfont", SetColor__5CFontFiiii);
INCLUDE_ASM("nonmatchings/cfont", SetColor__5CFontF10RGBAQ_TYPE);
INCLUDE_ASM("nonmatchings/cfont", SetColor__5CFontFUi);
INCLUDE_ASM("nonmatchings/cfont", SetFuchi__5CFontFi);
INCLUDE_ASM("nonmatchings/cfont", SetStr__5CFontFPc);
INCLUDE_ASM("nonmatchings/cfont", GetGaijiFontNo__FPc);
INCLUDE_ASM("nonmatchings/cfont", GetGaijiLen__FUs);
INCLUDE_ASM("nonmatchings/cfont", GetAlphabeticalFontNo_uc__FUc);
INCLUDE_ASM("nonmatchings/cfont", GetAlphabeticalFontNo_cp__FPc);
INCLUDE_ASM("nonmatchings/cfont", GetFontGaijiFontNo__FPc);
INCLUDE_ASM("nonmatchings/cfont", GetAlphabeticalFontNo_us__FUs);
INCLUDE_ASM("nonmatchings/cfont", GetFontNoFromFontGaijiCode__FUs);
INCLUDE_ASM("nonmatchings/cfont", GetFontGaijiHankaku__FUs);
INCLUDE_ASM("nonmatchings/cfont", GetFontNo__FPc);
INCLUDE_ASM("nonmatchings/cfont", GetHalfFontNo__Fc);
INCLUDE_ASM("nonmatchings/cfont", GetDigitNo__5CFontFi);
INCLUDE_ASM("nonmatchings/cfont", set2DSpriteEasyFont__FP11mgCDrawPrim9mgRect_i_9mgRect_i_P10RGBAQ_TYPE);
INCLUDE_ASM("nonmatchings/cfont", set2DSprite_Fuchi__FP11mgCDrawPrim4RECT4RECTii);
INCLUDE_ASM("nonmatchings/cfont", DrawChar__5CFontFP11mgCDrawPrimiiii10RGBAQ_TYPEUc);
INCLUDE_ASM("nonmatchings/cfont", DrawChar__5CFontFP11mgCDrawPrimPcii);
INCLUDE_ASM("nonmatchings/cfont", MySetTex__FPcP11mgCDrawPrim);
INCLUDE_ASM("nonmatchings/cfont", MySetTex__FiP11mgCDrawPrim);
INCLUDE_ASM("nonmatchings/cfont", DrawGaiji_sub__FP11mgCDrawPrimiii10RGBAQ_TYPEi);
INCLUDE_ASM("nonmatchings/cfont", DrawGaiji__5CFontFP11mgCDrawPrimiii);
INCLUDE_ASM("nonmatchings/cfont", UpDateWH__FPiPiii);
INCLUDE_ASM("nonmatchings/cfont", CalcDrawWH__5CFontFPcPiPi);
INCLUDE_ASM("nonmatchings/cfont", DrawDirect__5CFontFPcii);
INCLUDE_ASM("nonmatchings/cfont", Preset__5CFontFi);
INCLUDE_ASM("nonmatchings/cfont", Init__5CFontFv);
INCLUDE_ASM("nonmatchings/cfont", Setup__10COcclusionFPA4_f);
INCLUDE_ASM("nonmatchings/cfont", CheckSphere__10COcclusionFPf);
INCLUDE_ASM("nonmatchings/cfont", CalcSelectCursorPos__F4RECTPi);
INCLUDE_ASM("nonmatchings/cfont", OffsetYesNoWin__FP4RECTP4RECT);
INCLUDE_ASM("nonmatchings/cfont", DrawVersatileWin_yesno__FP11mgCDrawPrim4RECTP10RGBAQ_TYPEii);
INCLUDE_ASM("nonmatchings/cfont", MyMenuHelpWinDraw__FP11mgCDrawPrim4RECTi);
INCLUDE_ASM("nonmatchings/cfont", MyMenuFloatingWinDraw__FP11mgCDrawPrim4RECTiiP10RGBAQ_TYPEP10RGBAQ_TYPE);
INCLUDE_ASM("nonmatchings/cfont", DrawVersatileWin_1__FP11mgCDrawPrim4RECTP10RGBAQ_TYPEii);
INCLUDE_ASM("nonmatchings/cfont", DrawVersatileWin_1__FP11mgCDrawPrim4RECTP10RGBAQ_TYPEi);
INCLUDE_ASM("nonmatchings/cfont", DrawVersatileWin_3__FP11mgCDrawPrim4RECTiP10RGBAQ_TYPEii);
INCLUDE_ASM("nonmatchings/cfont", DrawVersatileWin_4__FP11mgCDrawPrim4RECTP10RGBAQ_TYPEii);
INCLUDE_ASM("nonmatchings/cfont", DrawVersatileWin_4__FP11mgCDrawPrim4RECTP10RGBAQ_TYPEi);
INCLUDE_ASM("nonmatchings/cfont", DrawDQFukidashi__FP11mgCDrawPrim4RECTiiP10RGBAQ_TYPEii);
INCLUDE_ASM("nonmatchings/cfont", LoadGaijiImg__Fv);
INCLUDE_ASM("nonmatchings/cfont", GetGaijiImgPtr__Fv);
INCLUDE_ASM("nonmatchings/cfont", LoadFontTex2Img__Fv);
INCLUDE_ASM("nonmatchings/cfont", GetFontTex2ImgPtr__Fv);
INCLUDE_ASM("nonmatchings/cfont", CheckControl__Fv);
INCLUDE_ASM("nonmatchings/cfont", EditModeControlLock__Fv);
INCLUDE_ASM("nonmatchings/cfont", EditModeControlUnLock__Fv);
INCLUDE_ASM("nonmatchings/cfont", SetHelpMes__Fiii);
INCLUDE_ASM("nonmatchings/cfont", GetUserData__Fv_002DD7A0);
INCLUDE_ASM("nonmatchings/cfont", ConvColor__Ff);
INCLUDE_ASM("nonmatchings/cfont", ConvColorV__FPf);
INCLUDE_ASM("nonmatchings/cfont", emSearchColorCode__FPf);
INCLUDE_ASM("nonmatchings/cfont", emGetPenkiItemNo__Fi);
INCLUDE_ASM("nonmatchings/cfont", emGetPenkiItemNo__FPf);
INCLUDE_ASM("nonmatchings/cfont", IntiSystemMes__Fv);
INCLUDE_ASM("nonmatchings/cfont", OpenSystemMes__FP6CSceneii);
INCLUDE_ASM("nonmatchings/cfont", SystemMesClose__FP6CScene);
INCLUDE_ASM("nonmatchings/cfont", SystemMesStep__FP6CScene);
INCLUDE_ASM("nonmatchings/cfont", EditStartPlaceEffect__FP10CEditPartsPf);
INCLUDE_ASM("nonmatchings/cfont", EditEndPlaceEffect__Fv);
INCLUDE_ASM("nonmatchings/cfont", EditPreMenuAnime__Fi);
INCLUDE_ASM("nonmatchings/cfont", LoadEditCursor__FP9mgCMemoryi);
INCLUDE_ASM("nonmatchings/cfont", GetSelPartsInfoID__Fv);
INCLUDE_ASM("nonmatchings/cfont", ClearEditStepCnt__Fv);
INCLUDE_ASM("nonmatchings/cfont", ClearUndoFlag__Fv);
INCLUDE_ASM("nonmatchings/cfont", ClearEditFlag__Fv);
INCLUDE_ASM("nonmatchings/cfont", InitEditFlag__Fv);
INCLUDE_ASM("nonmatchings/cfont", StartEditMode__FP6CScene);
INCLUDE_ASM("nonmatchings/cfont", EndEditMode__FP6CScenePf);
INCLUDE_ASM("nonmatchings/cfont", StartEditModeFromMenu__FP6CSceneiPi);
INCLUDE_ASM("nonmatchings/cfont", GetUndoData__Fv);
INCLUDE_ASM("nonmatchings/cfont", UndoEnable__Fv);
INCLUDE_ASM("nonmatchings/cfont", UndoPlaceParts__FP6CScene);
INCLUDE_ASM("nonmatchings/cfont", StackUndoData__FP9UNDO_DATA);
INCLUDE_ASM("nonmatchings/cfont", StartEditPutWall__FPQ210CEditParts8WallInfo);
INCLUDE_ASM("nonmatchings/cfont", PlaceEditParts__FP8CEditMapPfPfP13EP_PLACE_INFO);
INCLUDE_ASM("nonmatchings/cfont", PlaceRiverStart__FP8CEditMapPf);
INCLUDE_ASM("nonmatchings/cfont", PlaceRiverStep__FP8CEditMap);
INCLUDE_ASM("nonmatchings/cfont", NowPlaceRiver__Fv);
INCLUDE_ASM("nonmatchings/cfont", RemoveMtnStart__FP8CEditMapPfPf);
INCLUDE_ASM("nonmatchings/cfont", RemoveMtnStep__FP6CScene);
INCLUDE_ASM("nonmatchings/cfont", RemoveEditParts__FP6CSceneiPf);
INCLUDE_ASM("nonmatchings/cfont", DeleteKanketuParts__FP6CSceneP8CEditMapPfi);
