/* CPosDataManage, CMenuPosDataManage, CRepairManager, CLevelUpEffect, CEffVerticalLine, CRepairEffect, CLevelUpEffectManager, CStarDust
 *
 * Unité découpée par `make carve` : 93 fonctions, 21036 octets, de
 * 0x0022C990 à 0x00231DD0. Chacune garde les instructions du disque
 * jusqu'à ce qu'elle soit écrite en C++, et l'ordre est celui des adresses,
 * que l'éditeur de liens attend.
 */

#include "common.h"

INCLUDE_ASM("nonmatchings/cposdatamanage", Initialize__14CPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetTexGetInfo__14CPosDataManageFi);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetTexGetInfo__14CPosDataManageFPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetTexGetInfoTblNo__14CPosDataManageFPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", TexGetInfoClear__14CPosDataManageFii);
INCLUDE_ASM("nonmatchings/cposdatamanage", ResetTextureBlockNo__14CPosDataManageFPci);
INCLUDE_ASM("nonmatchings/cposdatamanage", ResetTextureInfoAll__14CPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", EtcTblClear__14CPosDataManageFii);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetEtcTbl__14CPosDataManageFPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetEtcTblValue__14CPosDataManageFPcRiRi);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetEtcTbl2__14CPosDataManageFPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetEtcTbl2Value__14CPosDataManageFPcPfi);
INCLUDE_ASM("nonmatchings/cposdatamanage", EtcTbl2Clear__14CPosDataManageFii);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetMenuMainIconChar__Fi);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetFormInfo__14CPosDataManageFPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetFormInfo__14CPosDataManageFi);
INCLUDE_ASM("nonmatchings/cposdatamanage", FormInfoClear__14CPosDataManageFii);
INCLUDE_ASM("nonmatchings/cposdatamanage", SetFormPos__14CPosDataManageFPcPi);
INCLUDE_ASM("nonmatchings/cposdatamanage", InitDrawList__14CPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetDrawTopList__14CPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", FormReLink__14CPosDataManageFPcPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", FormReLink2__14CPosDataManageFPcPcPcPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", FormStep__14CPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", MenuDrawParamStep__Fv);
INCLUDE_ASM("nonmatchings/cposdatamanage", FormDraw__14CPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", ClearPos__14CPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", AttachCommonTexInfo__18CMenuPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", StepMainMenuIconMove__18CMenuPosDataManageFPiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", CheckItemUseVariable__FP13CGameDataUsedP14CItemUseTarget);
INCLUDE_ASM("nonmatchings/cposdatamanage", Func_MenuItemBrdPrepare__FP18MENUFORMPARTS_TYPEP13CGameDataUsedP13CGameDataUsedi);
INCLUDE_ASM("nonmatchings/cposdatamanage", Func_MenuItemBrdPrepare2__FP18MENUFORMPARTS_TYPEP13CGameDataUsedP13CGameDataUsed);
INCLUDE_ASM("nonmatchings/cposdatamanage", NowUseNeedItemCheck__FP16CUserDataManager);
INCLUDE_ASM("nonmatchings/cposdatamanage", Func_MenuIconDrawPrepare__FP18MENUFORMPARTS_TYPEP13CGameDataUsedi);
INCLUDE_ASM("nonmatchings/cposdatamanage", CheckItemBoardFunc_MenuIconDrawPrepare__FP16CUserDataManagerP18MENUFORMPARTS_TYPE);
INCLUDE_ASM("nonmatchings/cposdatamanage", MenuItemBrdScrlBarStep__Fiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", Func_MenuItemBrdPosStep__Fi);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetPosMenuItemBrdKoma__18CMenuPosDataManageFPiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetPosMenuItemOnItemBrd__18CMenuPosDataManageFPiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", GetPosMenuItemBrdForEffect__18CMenuPosDataManageFPiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", Func_MenuItemIconSetEffectOne__FP18MENUFORMPARTS_TYPE);
INCLUDE_ASM("nonmatchings/cposdatamanage", MenuItemBrdItemIconEffectMalloc__FP9mgCMemoryP18MENUFORMPARTS_TYPEi);
INCLUDE_ASM("nonmatchings/cposdatamanage", MallocPallet__18CMenuPosDataManageFP9mgCMemory);
INCLUDE_ASM("nonmatchings/cposdatamanage", SearchTransPalletNo__18CMenuPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", InitializeCMenuPosDataManage__18CMenuPosDataManageFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", MenuCapture__FiP9mgCMemoryi);
INCLUDE_ASM("nonmatchings/cposdatamanage", SetBGFrameForMenu__FiPc);
INCLUDE_ASM("nonmatchings/cposdatamanage", MenuFrameImageDraw__FP11mgCDrawPrimP10mgCTexture9mgRect_f_9mgRect_i_iii);
INCLUDE_ASM("nonmatchings/cposdatamanage", Initialize__13CRepairEffectFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__13CRepairEffectFP9mgCMemoryi);
INCLUDE_ASM("nonmatchings/cposdatamanage", Step__13CRepairEffectFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Draw__13CRepairEffectFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Initialize__14CRepairManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", SetStack__14CRepairManagerFP9mgCMemoryi);
INCLUDE_ASM("nonmatchings/cposdatamanage", Clear__14CRepairManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", LoadDataBG__14CRepairManagerFP9mgCMemory);
INCLUDE_ASM("nonmatchings/cposdatamanage", CheckDataBG__14CRepairManagerFi);
INCLUDE_ASM("nonmatchings/cposdatamanage", SetRepairData__14CRepairManagerFP9mgCMemoryiPUi);
INCLUDE_ASM("nonmatchings/cposdatamanage", GeneratePoly__14CRepairManagerFPfi);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__14CRepairManagerFii);
INCLUDE_ASM("nonmatchings/cposdatamanage", IsRunModel__14CRepairManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", IsRun__14CRepairManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Step__14CRepairManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Draw__14CRepairManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Initialize__14CLevelUpEffectFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__14CLevelUpEffectFP10mgCTextureiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__14CLevelUpEffectFP10mgCTextureiP11CCharacter2);
INCLUDE_ASM("nonmatchings/cposdatamanage", IsRun__14CLevelUpEffectFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Step__14CLevelUpEffectFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Draw__14CLevelUpEffectFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Initialize__21CLevelUpEffectManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", IsRun__21CLevelUpEffectManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__21CLevelUpEffectManagerFiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__21CLevelUpEffectManagerFiP11CCharacter2);
INCLUDE_ASM("nonmatchings/cposdatamanage", Step__21CLevelUpEffectManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Draw__21CLevelUpEffectManagerFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__9CStarDustFiiii);
INCLUDE_ASM("nonmatchings/cposdatamanage", Step__9CStarDustFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Draw__9CStarDustFP10mgCTextureii);
INCLUDE_ASM("nonmatchings/cposdatamanage", CheckNotRunStarDust__FP9CStarDusti);
INCLUDE_ASM("nonmatchings/cposdatamanage", CheckRunStarDust__FP9CStarDusti);
INCLUDE_ASM("nonmatchings/cposdatamanage", Generate__16CEffVerticalLineFPfff);
INCLUDE_ASM("nonmatchings/cposdatamanage", Step__16CEffVerticalLineFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", Draw__16CEffVerticalLineFv);
INCLUDE_ASM("nonmatchings/cposdatamanage", InitInitBuildUpInfoEffectPos__Fv);
INCLUDE_ASM("nonmatchings/cposdatamanage", InitBuildUpInfoEffect__FP9mgCMemoryP10mgCTextureif);
INCLUDE_ASM("nonmatchings/cposdatamanage", SetBuildUpInfoChara__FP11CCharacter2f);
INCLUDE_ASM("nonmatchings/cposdatamanage", StepBuildUpInfoEffect__Fv);
INCLUDE_ASM("nonmatchings/cposdatamanage", DrawBuildUpInfoEffect__Fv);
INCLUDE_ASM("nonmatchings/cposdatamanage", InitFishBoiledEffect__FPiP10mgCTexture);
INCLUDE_ASM("nonmatchings/cposdatamanage", StepFishBoiledEffect__Fv);
INCLUDE_ASM("nonmatchings/cposdatamanage", DrawFishBoiledEffect__Fv);
INCLUDE_ASM("nonmatchings/cposdatamanage", SetEffectSpectolBreak__FP9mgCMemoryP11CMenuEffecti);
INCLUDE_ASM("nonmatchings/cposdatamanage", SetEffectSpectolFusion__FP9mgCMemoryPP11CMenuEffectP13CGameDataUsedi);
