/* CScene, CRain, CMap, SCN_LOADMAP_INFO2, CSceneMessage, CSceneCamera, CSceneSky, CSceneEffect, CSceneMap, CSceneCharacter, CSceneData, CSceneGameObj, mgCObjectStack_21CList_12EMAP_MESSAGE__
 *
 * Unité découpée par `make carve` : 94 fonctions, 15700 octets, de
 * 0x00285F50 à 0x00289E48. Chacune garde les instructions du disque
 * jusqu'à ce qu'elle soit écrite en C++, et l'ordre est celui des adresses,
 * que l'éditeur de liens attend.
 */

#include "common.h"

INCLUDE_ASM("nonmatchings/cscene", SetCharNo__5CRainFi);
INCLUDE_ASM("nonmatchings/cscene", ParticleBirth__5CRainFPfi);
INCLUDE_ASM("nonmatchings/cscene", Stop__5CRainFv);
INCLUDE_ASM("nonmatchings/cscene", Start__5CRainFv);
INCLUDE_ASM("nonmatchings/cscene", Step__5CRainFv);
INCLUDE_ASM("nonmatchings/cscene", Init__5CRainFv);
INCLUDE_ASM("nonmatchings/cscene", DrawScreenRain__Fv);
INCLUDE_ASM("nonmatchings/cscene", Draw__5CRainFv);
INCLUDE_ASM("nonmatchings/cscene", Initialize__10CSceneDataFv);
INCLUDE_ASM("nonmatchings/cscene", AssignData__15CSceneCharacterFP11CCharacter2Pc);
INCLUDE_ASM("nonmatchings/cscene", Initialize__15CSceneCharacterFv);
INCLUDE_ASM("nonmatchings/cscene", Initialize__9CSceneMapFv);
INCLUDE_ASM("nonmatchings/cscene", AssignData__9CSceneMapFP4CMapPc);
INCLUDE_ASM("nonmatchings/cscene", Initialize__13CSceneMessageFv);
INCLUDE_ASM("nonmatchings/cscene", AssignData__13CSceneMessageFP6ClsMesPc);
INCLUDE_ASM("nonmatchings/cscene", AssignData__12CSceneCameraFP9mgCCameraPc);
INCLUDE_ASM("nonmatchings/cscene", Initialize__12CSceneCameraFv);
INCLUDE_ASM("nonmatchings/cscene", AssignData__9CSceneSkyFP7CMapSkyPc);
INCLUDE_ASM("nonmatchings/cscene", Initialize__9CSceneSkyFv);
INCLUDE_ASM("nonmatchings/cscene", Initialize__13CSceneGameObjFv);
INCLUDE_ASM("nonmatchings/cscene", Initialize__12CSceneEffectFv);
INCLUDE_ASM("nonmatchings/cscene", AssignData__12CSceneEffectFP16CEffectScriptManPc);
INCLUDE_ASM("nonmatchings/cscene", InitAllData__6CSceneFv);
INCLUDE_ASM("nonmatchings/cscene", Initialize__6CSceneFv);
INCLUDE_ASM("nonmatchings/cscene", SetStack__6CSceneFiP9mgCMemory);
INCLUDE_ASM("nonmatchings/cscene", GetStack__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", ClearStack__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", AssignStack__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSceneCharacter__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSceneMap__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSceneMessage__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSceneCamera__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSceneSky__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSceneGameObj__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSceneEffect__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", CheckIMGName__6CSceneFiPc);
INCLUDE_ASM("nonmatchings/cscene", CheckMDSName__6CSceneFiPc);
INCLUDE_ASM("nonmatchings/cscene", GetData__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", AssignCamera__6CSceneFiP9mgCCameraPc);
INCLUDE_ASM("nonmatchings/cscene", GetCameraID__6CSceneFPc);
INCLUDE_ASM("nonmatchings/cscene", GetCamera__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", AssignMessage__6CSceneFiP6ClsMesPc);
INCLUDE_ASM("nonmatchings/cscene", GetMessage__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", AssignChara__6CSceneFiP11CCharacter2Pc);
INCLUDE_ASM("nonmatchings/cscene", SetCharaNo__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", GetCharaNo__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetCharacter__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", AssignMap__6CSceneFiP4CMapPc);
INCLUDE_ASM("nonmatchings/cscene", GetMapName__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetMapID__6CSceneFPc);
INCLUDE_ASM("nonmatchings/cscene", GetMap__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetSky__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetMainMapNo__6CSceneFv);
INCLUDE_ASM("nonmatchings/cscene", InScreenFunc__6CSceneFP16InScreenFuncInfo);
INCLUDE_ASM("nonmatchings/cscene", DrawScreenFunc__6CSceneFP8mgCFrame);
INCLUDE_ASM("nonmatchings/cscene", AssignSky__6CSceneFiP7CMapSkyPc);
INCLUDE_ASM("nonmatchings/cscene", DeleteSky__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", AssignEffect__6CSceneFiP16CEffectScriptManPc);
INCLUDE_ASM("nonmatchings/cscene", DeleteEffect__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", GetEffect__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", StepEffectScript__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", DrawEffectScript__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", IsActive__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", SetActive__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", ResetActive__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", SetStatus__6CSceneFiii);
INCLUDE_ASM("nonmatchings/cscene", ResetStatus__6CSceneFiii);
INCLUDE_ASM("nonmatchings/cscene", GetStatus__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", SetType__6CSceneFiii);
INCLUDE_ASM("nonmatchings/cscene", GetType__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", GetActiveMap__6CSceneFPP4CMapi);
INCLUDE_ASM("nonmatchings/cscene", GetCharaTexb__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", SetCharaTexb__6CSceneFii);
INCLUDE_ASM("nonmatchings/cscene", SetTime__6CSceneFf);
INCLUDE_ASM("nonmatchings/cscene", AddTime__6CSceneFf);
INCLUDE_ASM("nonmatchings/cscene", TimeStep__6CSceneFf);
INCLUDE_ASM("nonmatchings/cscene", SetWind__6CSceneFfPf);
INCLUDE_ASM("nonmatchings/cscene", ResetWind__6CSceneFv);
INCLUDE_ASM("nonmatchings/cscene", GetWind__6CSceneFPf);
INCLUDE_ASM("nonmatchings/cscene", SetNowMapNo__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", SetNowSubMapNo__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", LoadMapData__FR17SCN_LOADMAP_INFO2i);
INCLUDE_ASM("nonmatchings/cscene", Initialize__17SCN_LOADMAP_INFO2Fv);
INCLUDE_ASM("nonmatchings/cscene", LoadChara__6CSceneFiPUiPcP9mgCMemoryP9mgCMemoryP9mgCMemoryii);
INCLUDE_ASM("nonmatchings/cscene", DeleteChara__6CSceneFi);
INCLUDE_ASM("nonmatchings/cscene", CopyChara__6CSceneFiiP9mgCMemory);
INCLUDE_ASM("nonmatchings/cscene", LoadMapFromMemory__6CSceneFiP17SCN_LOADMAP_INFO2);
INCLUDE_ASM("nonmatchings/cscene", LoadMapFromMemory__6CSceneFiiP17SCN_LOADMAP_INFO2);
INCLUDE_ASM("nonmatchings/cscene", Initialize__39mgCObjectStack_21CList_12EMAP_MESSAGE__Fv);
INCLUDE_ASM("nonmatchings/cscene", __ct__4CMapFv);
INCLUDE_ASM("nonmatchings/cscene", LoadMapBGStep__6CSceneFP17SCN_LOADMAP_INFO2);
INCLUDE_ASM("nonmatchings/cscene", LoadMap__6CSceneFiP17SCN_LOADMAP_INFO2i);
INCLUDE_ASM("nonmatchings/cscene", __as__17SCN_LOADMAP_INFO2FRC17SCN_LOADMAP_INFO2);
INCLUDE_ASM("nonmatchings/cscene", DeleteMap__6CSceneFii);
