/* mgCVisualMotionMDT, CTreasureBoxManager, CStartupEpisodeTitle, CRandomCircle, MessageTaskManager, CGeoStone, CTreasureBox, CRedMarkModel, mgVertexWeight, CSound
 *
 * Unité découpée par `make carve` : 98 fonctions, 24196 octets, de
 * 0x0028D160 à 0x002931B0. Chacune garde les instructions du disque
 * jusqu'à ce qu'elle soit écrite en C++, et l'ordre est celui des adresses,
 * que l'éditeur de liens attend.
 */

#include "common.h"

INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", __make_fp);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", fptodp);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", LoadFileSocket__FPcPUi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", WriteFileSocket__FPcPUii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Initialize__18mgCVisualMotionMDTFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CreateVertexWeight__18mgCVisualMotionMDTFPUiiP9mgCMemory);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", __ct__14mgVertexWeightFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", ChangeWeight__18mgCVisualMotionMDTFPP8mgCFramePA4_A4_fi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DataAssignMotionMDT__18mgCVisualMotionMDTFP10MDT_HEADERP14mgCVMotionDataP9mgCMemoryP9mgCMemoryP17mgCTextureManager);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData0__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData1__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData2__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData3__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData4__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData5__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData6__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetData7__FiiPPiP1P1P1P1P1P14mgVertexWeight);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CreateFaceMotionPacket__18mgCVisualMotionMDTFPUiP7mgCFaceP14mgCVMotionData);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CreateRenderInfoPacket__18mgCVisualMotionMDTFPUiPA4_fP13mgRENDER_INFO);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CreateExtRenderInfoPacket__18mgCVisualMotionMDTFPUiPA4_fP13mgRENDER_INFO);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetBaseBox__18mgCVisualMotionMDTFPfPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CreateBBox__18mgCVisualMotionMDTFPfPfPA4_f);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Copy__18mgCVisualMotionMDTFP9mgCMemory);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Iam__18mgCVisualMotionMDTFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", ezBgmInit__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", ezBgm__Fii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", StreamOpenState__6CSoundFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DrawEpisode__20CStartupEpisodeTitleFii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Switch__20CStartupEpisodeTitleFi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Step__20CStartupEpisodeTitleFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Initialize__20CStartupEpisodeTitleFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Draw__18MessageTaskManagerFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Step__18MessageTaskManagerFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Print__18MessageTaskManagerFPciii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Clear__18MessageTaskManagerFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Initialize__18MessageTaskManagerFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Draw__13CRedMarkModelFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Step__13CRedMarkModelFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", GeoDraw__9CGeoStoneFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DrawMiniMapSymbol__9CGeoStoneFP14CMiniMapSymbol);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetFlag__9CGeoStoneFi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", GeoStep__9CGeoStoneFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CheckEvent__9CGeoStoneFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Initialize__9CGeoStoneFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Draw__13CRandomCircleFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Step__13CRandomCircleFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DrawSymbol__13CRandomCircleFP14CMiniMapSymbol);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CheckArea__13CRandomCircleFPff);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", GetPosition__13CRandomCircleFPfi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CheckEvent__13CRandomCircleFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetCircle__13CRandomCircleFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Clear__13CRandomCircleFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Initialize__13CRandomCircleFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Draw__12CTreasureBoxFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DrawShadow__12CTreasureBoxFPfPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetLargeModel__19CTreasureBoxManagerFP11CCharacter2i);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SetCollisionModel__19CTreasureBoxManagerFPUiP9mgCMemory);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", PutTreasureBox__19CTreasureBoxManagerFiPffiiiii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CheckArea__19CTreasureBoxManagerFPff);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DrawMiniMapSymbol__19CTreasureBoxManagerFP14CMiniMapSymbol);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Draw__19CTreasureBoxManagerFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DrawShadow__19CTreasureBoxManagerFPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", PickupCollision__19CTreasureBoxManagerFPfP6CCPoly9mgVu0FBOXi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", MimicCount__19CTreasureBoxManagerFv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CheckEvent__19CTreasureBoxManagerFPff);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", GetGateKeyIndex__Fii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", GetKeyDoorIndex__Fii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", Lamb2WolfManager__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", LoopSoundManager__Fi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", BattleSoundManager__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", StatusWarningSnd__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", BattleAreaBGMCtrl__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", ScriptDebugCommand__Fi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", XChgMapLighting__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", XChgMapRotation__Fi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SearchMapEventParts__FiPP9CMapPartsPfi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", SearchMapFlatPosition__FPfP11CAutoMapGen);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", GetDungeonEventPoint__FPfPfi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _GROUP_START__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _GROUP__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _ITEM__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _FLOOR_START__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _FLOOR__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CreatTresuarBoxInfo__FP22TRESURE_BOX_FLOOR_INFOPci);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", PickupRandomItemCheckMax__FP22TRESURE_BOX_FLOOR_INFOi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", PickupRandomItem__FP22TRESURE_BOX_FLOOR_INFOii);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CheckObjectPutArea__FPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", ScanEyePoint__FPf);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", AutoSetTreasureBox__FiPff);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", AutoSetTreasureBox__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _FLS__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _FL__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", _FLE__FP9SPI_STACKi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", CreatMonsterFloorInfo__FPci);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", AutoSetMonster__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", AutoSetMonster__FiPfPfi);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DungeonFloorInit__Fv);
INCLUDE_ASM("nonmatchings/mgcvisualmotionmdt", DungeonFloorFinish__Fv);
